### PR TITLE
libxml2: add 2.12 variant

### PR DESCRIPTION
**Pull request by pauleve**
Updated workflow to use 2.12 libxml2 variant.

Can you update the online packages ?

### CODE REVIEW

**Comment by pauleve** [comment]
Ah I just saw https://github.com/vincent-noel/libsbml-plus-packages/commit/f020264b5227bc1ff38caf29bfa932e07cf7e758

But it will be fixed soon: https://github.com/sbmlteam/libsbml/commit/a3e217851f18d3c5e8e2b0082fb98176738491e8

(either we wait for the release, or we add the patch manually)

**Comment by vincent-noel** [comment]
Sorry for only seeing this now. 
I was going to wait, but this has taken more time than I thought :(

**Comment by vincent-noel** [comment]
This should be fixed now ! Let me know if it works.

**Comment by pauleve** [comment]
Works great, thanks!
Can you add the 2.13 variant as well?

**Pull request closed without merging**
